### ISSUE TITLE
[Question] How to pass nonce?

### ISSUE THREAD

**Issue by raphaeljlps** [dghubble/oauth1#1]
Hello @dghubble, I would like to know if there is a way to pass a oauth_nonce?

**Comment by dghubble** [comment]
I don't think so, it is not something I've needed in higher packages yet. What is your use case for a custom noncer?

The Config could potentially have a configurable Noncer to be used by the Signer.

    type Noncer interface {
       Nonce() string
    }

**Comment by raphaeljlps** [comment]
Ah, I tough about using Nonce to identify subsequent requests made by the same user in the flow of authenticating, but I saw that we can use the oauth_token to do this. 
Anyway, I was trying to treat the Nonce as the OAuth 2.0 state param.
Don't need anymore, thanks @dghubble 
I started to use you lib and found it pleasant to work with it :+1:
