### ISSUE TITLE
[Question] How to add headers to the request?

### ISSUE THREAD

**Issue by jryd** [dghubble/oauth1#16]
I am building a service in Go that queries a Magento API.

I already have the oauth credentials needed to make the request (these are persistent) and am able to successfully query the API in Postman.

I am trying to query the Magento API using this package, however every time I make the request I get an error:

> Service temporary unavailable

It appears this is a common error when the request is missing an "Accept" header.

How can I add an "Accept" header to my request?

**Comment by jryd** [comment]
This was achievable through the below:

```
func main() {

    config := oauth1.NewConfig("consumer key", "consumer secret")
    token := oauth1.NewToken("token key", "token secret")

    httpClient := config.Client(oauth1.NoContext, token)

    path := "https://www.example.com/api/rest/customers?limit=2&order=created_at&dir=DESC"
    req, err := http.NewRequest("GET", path, nil)
    if err != nil {
        log.Fatal(err)
    }
    req.Header.Add("Accept", "application/json")

    resp, err := httpClient.Do(req)
    if err != nil {
        log.Fatal(err)
    }
    defer resp.Body.Close()
    body, _ := ioutil.ReadAll(resp.Body)
    fmt.Printf("Raw Resonse Body:\n%v\n", string(body))
}
```

**Comment by dghubble** [comment]
Or the Authorizing Requests example: https://github.com/dghubble/oauth1#authorized-requests
