### ISSUE TITLE
1-legged Oauth1 support

### ISSUE THREAD

**Issue by anisse** [dghubble/oauth1#19]
Should there be a way to do one-legged OAuth1 ? Looking at the fork network, it seems at least one person needed such a feature:
https://github.com/athornz/oauth1/commit/cdb32072051dc45f6b4754d0d685a81aaf8d45da (hi @athornz )

What do you think ?

**Comment by dghubble** [comment]
APIs still using 1-legged mode?

**Comment by anisse** [comment]
That's a good question. This was for a private use, not a public API, and I ended up lifting @athornz's patch.

**Comment by dghubble** [comment]
Ok. I don't really want to support 1-legged flow without any API implementations in the wild.
