### ISSUE TITLE
Create a contribute.md

### ISSUE THREAD

**Issue by raphaeljlps** [dghubble/oauth1#2]
Hello @dghubble 
could you create a contribute.md for people like me that want to contribute to this project have some directions?

**Comment by dghubble** [comment]
Over the next week or so I'll be finishing up some refactoring I've been wanting to do to target a v1 and complete test coverage. I'll be sure to add a `CONTRIBUTING.md` file during that work to describe process going forward.

**Comment by dghubble** [comment]
A link to a contributing guide will be added in 26bff43eb728 for v1.0.0-rc1

**Comment by raphaeljlps** [comment]
Thanks @dghubble
