### ISSUE TITLE
OAuth2 like http client switching?

### ISSUE THREAD

**Issue by ktnyt** [dghubble/oauth1#24]
I've been developing on Google App Engine and stumbled across a problem where the `http.DefaultClient` is not available for use. The OAuth2 library circumvents this issue by swapping out the http client to use `urlfetch.Client` located in in "google.golang.org/appengine/urlfetch" when the "appengine" build tag is present. I was wondering if it would be fine if I created a pull request containing these changes (or, I'll just patch it for myself if it seems to niche to be a problem).

**Comment by arran4** [comment]
I have created a PR for a very minimalist change: https://github.com/dghubble/oauth1/pull/25

**Comment by dghubble** [comment]
I was really hoping either Google App Engine or the restriction on not being allowed to use `http.DefaultClient` would have disappeared by now.

**Comment by ktnyt** [comment]
I agree that the restriction is pretty BS. I guess I will have to live with what I have!
