### ISSUE TITLE
[Question] How to use the Authenticate Endpoint?

### ISSUE THREAD

**Issue by raphaeljlps** [dghubble/oauth1#3]
Hello @dghubble sorry to bother you
but I would like to know if there is a way to use the authenticate endpoint,
I think a function like AuthenticateURL is missing,
let me know if there is anything I can do to help.

**Comment by dghubble** [comment]
I'm not quite sure what your question is? If you are talking about redirecting an end-user to the authorization URL in the flow to get an access token, that is obtained by calling `Config.AuthorizationURL(rt *RequestToken) (*url.URL, error)` on your `Config` with the `RequestToken` from the previous step.

If you're asking about the `twitter` `AuthenticateEndpoint`, specify it as the `Endpoint` in your `Config`, Twitter provides two flavors of `Endpoint`.

    import (
        "github.com/dghubble/oauth1"
        "github.com/dghubble/oauth1/twitter"
    )
    ...
    config := &oauth1.Config{
		ConsumerKey:    "consumer_key",
		ConsumerSecret: "consumer_secret",
		CallbackURL:    "http://example.com/oauth/twitter/callback",
		Endpoint:       twitter.AuthenticateEndpoint,
	}

**Comment by dghubble** [comment]
The method signature `Config.AuthorizationURL(rt *RequestToken) (*url.URL, error)` will change to
`Config.AuthorizationURL(requestToken string) (*url.URL, error)` in #4.
